Update to Astyle 1.24 (latest 1.x release)
Summary:
Problems:
There was some debugging mechanism hacked into the astyle lib sources,
which added 'ASIgnore' & 'AS/Ignore' markers. Without this support,
generated sources contain these markers unconditionally and thus fail
the compilation:

```
projectmanagers/qmake/parser/qmakeast.h:13:1: error: expected
unqualified-id
<U+0001>!ASIgnore"!!
^
```

With the update to Astyle 1.24, this debugging mechanism got disabled.
(I don't really know what it's for...)

Also update generated sources, ran:
$ flex --yymore --nounistd -o kdev-pg-lexer.cc  kdev-pg-lexer.ll

Test Plan: Compiled kdevelop (the QMake plugin uses kdev-pg-qt)

Reviewers: #kdevelop, mwolff

Reviewed By: #kdevelop, mwolff

Subscribers: mwolff, kdevelop-devel

Differential Revision: https://phabricator.kde.org/D5326